"""add_bot_name_to_meetings

Revision ID: bb1ce091d837
Revises: 9e3599156453
Create Date: 2026-04-04 17:21:57.018938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1ce091d837'
down_revision = '9e3599156453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bot_responses_meeting', table_name='bot_responses')
    op.drop_index('idx_bot_responses_timestamp', table_name='bot_responses')
    op.create_index(op.f('ix_bot_responses_bot_id'), 'bot_responses', ['bot_id'], unique=False)
    op.create_index(op.f('ix_bot_responses_id'), 'bot_responses', ['id'], unique=False)
    op.create_index(op.f('ix_bot_responses_meeting_id'), 'bot_responses', ['meeting_id'], unique=False)
    op.add_column('meetings', sa.Column('bot_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'bot_name')
    op.drop_index(op.f('ix_bot_responses_meeting_id'), table_name='bot_responses')
    op.drop_index(op.f('ix_bot_responses_id'), table_name='bot_responses')
    op.drop_index(op.f('ix_bot_responses_bot_id'), table_name='bot_responses')
    op.create_index('idx_bot_responses_timestamp', 'bot_responses', ['timestamp'], unique=False)
    op.create_index('idx_bot_responses_meeting', 'bot_responses', ['meeting_id'], unique=False)
    # ### end Alembic commands ###