"""add has_voice_profile to users

Revision ID: f8a52e412ae7
Revises: 004_add_recording_fields
Create Date: 2026-03-15 17:36:00.429704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8a52e412ae7'
down_revision = '004_add_recording_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_samples')
    op.drop_table('digital_twins')
    op.alter_column('meetings', 'scheduled_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('meetings', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # Add column with default value for existing rows
    op.add_column('users', sa.Column('has_voice_profile', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_voice_profile')
    op.alter_column('meetings', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('meetings', 'scheduled_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_table('digital_twins',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('digital_twins_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('personality_traits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('communication_style', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_patterns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meeting_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('voice_trained', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='digital_twins_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='digital_twins_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('voice_samples',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('digital_twin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['digital_twin_id'], ['digital_twins.id'], name='voice_samples_digital_twin_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='voice_samples_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='voice_samples_pkey')
    )
    # ### end Alembic commands ###